title:              Cristina Junca
email:              cristina.junca23@gmail.com
description:        Backend Engineer · DevEx · Tech Writer
author:             Cristina Junca
baseurl:            ""
url:                "https://cristina-sirbu.github.io"

# Social Profiles
github_username:    cristina-sirbu
linkedin_username:  cristina-junca
# twitter_username:   cristina_sirbu4

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-M2Z0W7C1GH # out your google-analytics code
formspree:    mzzgnyvn # out your formspree email code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

highlighter: rouge
kramdown:
  input: GFM